//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Account
    {
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        public string UserName { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        public string Password { get; set; }
        [DisplayName("Quyền")]
        public Nullable<bool> Role { get; set; }
        [DisplayName("Họ và tên")]
        public string Name { get; set; }
        [Key]
        public int ID { get; set; }
    }
}
