//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Contact
    {
        [Key]
        public int ID { get; set; }
        [DisplayName("Họ và tên")]
        [Required(ErrorMessage = "Họ và tên không được để trống")]
        public string Name { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email không được để trống")]
        public string Email { get; set; }
        [DisplayName("Nội dung")]
        [AllowHtml]
        public string Contents { get; set; }
        [DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> Date { get; set; }
        [DisplayName("Tình trạng")]
        public Nullable<bool> Seen { get; set; }
    }
}
