//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_WebEntities : DbContext
    {
        public Project_WebEntities()
            : base("name=Project_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Infomation> Infomations { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsCatalog> NewsCatalogs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductsCatalog> ProductsCatalogs { get; set; }
    }
}
