//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Product
    {
        [Key]
        public int ID { get; set; }
        [DisplayName("Mã code")]
        [Required(ErrorMessage = "Mã code không được để trống")]
        public string Code { get; set; }
        [DisplayName("Thông tin")]
        [Required(ErrorMessage = "Thông tin không được để trống")]
        public string Name { get; set; }
        [DisplayName("Mô tả sản phẩm")]
        [AllowHtml]
        public string Description { get; set; }
        [DisplayName("Hình ảnh")]
        public string Image { get; set; }
        [DisplayName("Tên danh mục")]
        public Nullable<int> ProductsCatalogID { get; set; }
    
        public virtual ProductsCatalog ProductsCatalog { get; set; }
    }
}
